### ISSUE TITLE
quais os estabelecimentos que o usuário pode ter acesso?

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#1]
Na Tela de cadastro de Usuários,Senti falta na tela de uma forma de indicar quais os estabelecimentos que o usuário pode ter acesso.

**Comment by engrogerio** [comment]
Em um email de 23/8/2016, perguntei:

		1 O sistema deve ter permissão por Unidade, ou todos os usuários poderão visualizar os registros de todas as unidades? Isso poderá ser alterado no futuro?

		Você me respondeu:
		1)      Não é necessário que o sistema tenha permissão por unidade., mas sim por usuário.
		
Preciso de esclarecimento neste ítem. Precisamos de permissões a nível de usuário ou não?

**Comment by angelitakoehler** [comment]
Acho que não nos entendemos nas respostas.
O que tentei te responder, é que o permissionamento não é feito para a unidade e sim para o usuário.

Tanto que na especificação isto é solicitado, observe no documento de especificação (Detalhamento Informações OTIF.xlsx), na pasta segurança estão sendo solicitados algumas associações:
> Perfil x tela
> Usuário x Perfil
> Usuário x Estabelecimento (filial)
A última parte foi o que não encontrei.

**Comment by engrogerio** [comment]
Um usuario pode acessar 2 ou mais estabelecimentos (unidades)?
Neste caso, ele deve ter as mesmas permissões nas unidades que ele tem acesso?
Fui claro na pergunta?

**Comment by angelitakoehler** [comment]
Sim, ele pode acessar apenas uma unidade ou pode acessar mais de uma, teremos usuários que poderão acessar todas as unidades.
As permissões para o usuário podem ser as mesmas em todas as unidades onde ele tem acesso.

**Comment by engrogerio** [comment]
Hoje na aplicação, temos os objetos:
Unidades, Cliente, Faltas, Multas, Grades e Pedidos.
Quais devem ter restrição de acesso por unidade?
Por exemplo, se Cliente tiver restrição por unidade, somente os usuários com permissão de acesso a esta(s) unidade(s) poderão visualiza-los.O mesmo para os outros objetos...

**Comment by angelitakoehler** [comment]
Não sei o que é a unidade e a falta que você cita.
A de cliente, se entendi bem é a tela onde cadastram os limites permitidos de atraso, isto não precisa restrição por estabelecimento, pois quem puder definir o limite pode para todos os clientes, visto que não é um limite para cada estabelecimento.
As demais sim, devem ter.
O mais importante é que a tela de carregamento e de grade respeitem esta restrição, que o usuário somente tenha acesso aos dados do(s) estabelecimento(s) liberado(s) para ele.

**Comment by engrogerio** [comment]
unidade = estabelecimento. Vou alterar...
Ok. Vou considerar quanto a necessidade de permissão por estabelecimento:
Cliente (cadastro de limites de atraso) - Não: Usuarios de todas as unidades verão todos.
Carregamento - Sim
Cadastro de estabelecimentos - Sim
Grades - Sim
Multas - Sim

**Comment by engrogerio** [comment]
O acesso aos dados do próprio estabelecimento é implícito ou explícito? Ou seja,  um usuário sempre terá acesso aos dados de seu estabelecimento ou deve ser selecionado o seu próprio estabelecimento na lista de estabelecimentos visíveis para o usuário?

**Comment by angelitakoehler** [comment]
ok - validei e está trazendo apenas o que o usuário tem acesso, neste momento como tenho apenas movimentos de um estabelecimento se escolho aquele está mostrando, se coloco para outro, não traz nada.
