### ISSUE TITLE
Tela de Carregamento - Campo para o numero dos pallets

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#10]
Não está solicitando o número dos pallets mesmo quando informo a quantidade destes.

**Comment by engrogerio** [comment]
Entendi. Vou adicionar campos para indicar os numeros dos pallets.

**Comment by angelitakoehler** [comment]
Ok, mas observe que isto não é em nível de item e sim de carregamento.
Veja documento de especificação (Detalhamento Informações OTIF.xlsx) pasta Expedição.

**Comment by angelitakoehler** [comment]
Rogerio, confirmei com a Cris Guedes, conforme havíamos falado no call, e esta informação do número do Pallet, ela vai precisar fazer consultas nela, e rastrear um determinado pallet.
Portanto acho melhor você ter uma amarração de pallet por nota, informando somente um número por campo, pois acredito que o rastreamento será melhor.

**Comment by engrogerio** [comment]
https://gist.github.com/jonashaag/1200165
