### ISSUE TITLE
Tela de carregamento - Campo de Observações

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#11]
Não encontrei campo para informar as observações.

**Comment by engrogerio** [comment]
Esse campo deve estar no carregamento?  Por favor, confirme.

**Comment by angelitakoehler** [comment]
Sim, observe o documento de especificações (Detalhamento Informações OTIF.xlsx), na pasta Expedição.
O campo observações é solicitado em nível de nota e não de item.

**Comment by angelitakoehler** [comment]
Agora temos o campo, mas está muito pequeno, as observações serão provavelmente grandes.
O campo permite que eu digite um texto grande, mas a visualização na tela está pequena, dificultando a interação e leitura do mesmo.

**Comment by engrogerio** [comment]
Alterado para 40 colunas x 4 linhas

**Comment by angelitakoehler** [comment]
Continuo vendo o campo com o mesmo tamanho.

**Comment by angelitakoehler** [comment]
Ok! agora o tamanho do campo na tela está adequado.
