### ISSUE TITLE
Tela de Carregamento - Não pode inserir items manualmente.

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#12]
- Está permitindo inserir manualmente itens que não constam na nota (não consegui entender e isto é opção liberável pelo controle de acessos), mas não foi originalmente solicitado que permitisse inserir itens que não constam da nota.

**Comment by engrogerio** [comment]
Realmente, não faz sentido. Será excluido.

**Comment by angelitakoehler** [comment]
Ok pode encerrar.
