### ISSUE TITLE
Tela de Fill Rate - Campo de motivo

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#13]
Está solicitando informar um motivo que não foi solicitado - porém este motivo é o que originalmente foi solicitado que fosse informado no carregamento.Para este caso deveria estar informado apenas o valor da multa

**Comment by engrogerio** [comment]
Essa explicação está meio confusa... poderia elaborar melhor o que você precisa?

**Comment by angelitakoehler** [comment]
Na tela de cadastro das multas de fill rate, apenas o valor da multa deve ser cadastrado, não há motivo, o motivo já é o fill rate.
Observei que nesta tela você está solicitando o motivo que na especificação original foi solicitado para ser informado pela expedição.
Observe no documento enviado a você (Detalhamento Informações OTIF.xlsx), na pasta Expedição que é lá que este motivo está sendo solicitado pois se a falta é detectada no carregamento, são eles que tem que informar o motivo.

**Comment by angelitakoehler** [comment]
Ok pode encerrar.
