### ISSUE TITLE
Tela Fill Rate - Não permite inserir um registro.

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#14]
Não está permitindo inserir um registro, está apenas trazendo os registros onde o carregamento disse que houve falta, não deverão ser sugeridos nenhum registro, deverá ser possível incluir registro de qualquer nota/item, pois apesar de no carregamento não estar registrado a falta, o cliente poderá constatar falta na entrega.
Somente deverão aparecer nesta lista, registros que já foram inseridos pela área responsável com a informação da multa, estão vindo todos os itens que o carregamento informou que houve falta.

**Comment by engrogerio** [comment]
O campo motivo deve ser modificável na tela de Fill Rate?

**Comment by angelitakoehler** [comment]
Motivo não... Se quiser pode até colocar um campo de observações, mas aquele motivo é apenas para a expedição registrar.
mas novamente não está compreendido a finalidade da tela.

O que eu citei neste ponto foi:
- Está trazendo TUDO e não deveria.
Somente deveria trazer aquilo que já tem a multa registrada, e permitir incluir as multas novas.

No momento que recebemos uma multa, o usuário deverá entrar nesta tela escolher a nota envolvida na multa e registrar a multa.
"Possivelmente", para os carregamentos onde foi registrado falta, haverá multa, mas isto não é obrigatório.
Podemos ter multa em um carregamento que a  expedição não registrou falta, mas que o cliente observou falta e foi confirmado a falta na entrega.
Deve ser permitido registrar esta multa também e será em fill rate.

**Comment by angelitakoehler** [comment]
Continuo não conseguindo incluir uma multa em uma nota que não está na lista.
Não sei como fazer isto tem opção?

**Comment by angelitakoehler** [comment]
Agora está oK,
