### ISSUE TITLE
Tela de Fill Rate - Permitir consultar por filtro no número de NF, número do Pedido e número da ordem de compra.

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#15]
Não está sendo possível consultar um registro através de um filtro como por exemplo o número da nota ou do pedido ou da ordem de compra, deveria permitir este tipo de consulta

**Comment by engrogerio** [comment]
Acrescentar estes 3 campos no campo de pesquisa é suficiente?

**Comment by angelitakoehler** [comment]
Eu preciso ter uma forma de encontrar a nota na qual vou registrar a multa.
estes 3 campos são uma forma, outra forma é informando o cliente.

**Comment by angelitakoehler** [comment]
Estou conseguindo pesquisar, porém somente está funcionando se for pelo número da nota.

**Comment by angelitakoehler** [comment]
Continuo conseguindo pesquisar apenas pelo número da nota.
Deveria ser possível pesquisar por mais informações.
Além do número da nota, uma das mais importantes é a ordem de compra que não  encontrei em nenhuma tela.

**Comment by angelitakoehler** [comment]
Além da NF, permitir também por:
- Cliente
- Pedido
- Ordem de compra

**Comment by engrogerio** [comment]
Ok. Será implementado

**Comment by engrogerio** [comment]
Feito

**Comment by angelitakoehler** [comment]
OK!
