### ISSUE TITLE
Tela no show deve ter botão para incluir registro.

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#16]
Não tem botão para incluir registro

**Comment by engrogerio** [comment]
A lista inicial da tela de No Show, devem aparecer os carregamentos filtrados de alguma forma? Só os que estão marcados como no Show?

**Comment by angelitakoehler** [comment]
Volto a afirmar que você não entendeu a finalidade.
nesta tela devo incluir  todas as notas que receberam multa deste tipo e os valores de multa que foram aplicados.
A multa de no-show pode ser por não comparecimento mesmo (no-show = S) ou por atraso no agendamento (no-show=N).
Ou seja, é exatamente nesta tela (e somente nesta) que vou informar o no-show S/N, na tela de carregamento não deve ter esta informação, afinal ali não sei disso.

**Comment by angelitakoehler** [comment]
Ok, agora estou conseguindo incluir.
