### ISSUE TITLE
Tela no show traz busca de consulta vazia

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#17]
Tela no show não está buscando nada na consulta/pesquisa

**Comment by engrogerio** [comment]
Temos 2 opções de buscar registros:
1- Para opções limitadas a uma certa quantidade: Ex. Clientes, Estabelecimentos, etc , usamos o FILTRO que aparece à direita (ver no caso da tela de carregamentos que tem as opções "Cod. estab." e "Status")
2- Para opções ilimitadas , Ex: Numero de NF, numero de pedido, etc. usamos o campo de PESQUISA.
Para a tela de No Show, quais campos você necessita para cada opção que eu citei aí em cima?

**Comment by engrogerio** [comment]
Temos 2 opções de buscar registros:
1- Para opções limitadas a uma certa quantidade: Ex. Clientes, Estabelecimentos, etc , usamos o FILTRO que aparece à direita (ver no caso da tela de carregamentos que tem as opções "Cod. estab." e "Status")
2- Para opções ilimitadas , Ex: Numero de NF, numero de pedido, etc. usamos o campo de PESQUISA.

*Para a tela de No Show, quais campos você necessita para cada opção que eu citei aí em cima?
*A lista de Carregamentos No Show deve mostrar somente os marcados com NoShow="S" ?

**Comment by angelitakoehler** [comment]
Onde e que o registro foi marcado como NoShow="S" se é nesta tela que informo isso?

Preciso ter uma forma de encontrar a nota que está recebendo a multa para poder registrar.
seja pesquisando pelo cliente, pela nota, pedido, ordem de compra.. algo
O que preciso é conseguir encontrar a nota e incluir a informação de multa para ela.

Acho que somente quando você entender a finalidade desta tela irá entender o que estou falando.

**Comment by angelitakoehler** [comment]
Observei que na tela de No show tem alguns registros mas não entendi como incluir uma multa para uma nota, tentei incluir uma nota mas não retorna na pesquisa e não tem botão de incluir.

**Comment by angelitakoehler** [comment]
Ok, agora entendi como consultar/incluir.
