### ISSUE TITLE
Não encontrei o campo Ordem de Compra

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#22]
Não encontrei em nenhuma tela o campo ordem de compra.
Este campo é muito importante em especial nas telas de Fill rate e No Show.

**Comment by engrogerio** [comment]
Acrescentado na tela de Fill Rate.
O campo "Ordem de compra" é relativo aos ítens do Carregamento.Se for colocado na tela de No Show (relativo a carregamentos), aparecerão várias linhas - uma para cada ítem do pedido ou uma para cada Ordem de compra envolvida no carregamento.
Temos que pensar melhor neste ponto.

**Comment by angelitakoehler** [comment]
Rogerio,
No caso da Aryzta ela faz apenas um pedido por nota.
Por este motivo a ordem de compra é sempre a mesma para todos os itens da nota.
Isto ocorre porque o cliente nos envia o pedido e muitas vezes informa o pedido dele (que é armazenado com ordem de compra em nosso sistema).
Na maioria das vezes quando o cliente nos impõe uma nota, seja por fill rate seja por no-show, ele nos informa apenas a ordem de compra que originou a multa, por este motivo é mais fácil consultar por este campo nas multas.

**Comment by engrogerio** [comment]
Eu sei que já conversamos sobre isso, mas para ficar registrado aqui.
Posso considerar que NF, Numero do Pedido e Numero de Ordem de compra são campos do Carregamento somente? Ou seja, cada carregamento é feito para ítens de uma mesma NF, mesmo pedido e mesma ordem de compra?

**Comment by angelitakoehler** [comment]
Sim, pode considerar que cada NF possui um único pedido e ordem de compra.
Att

**Comment by engrogerio** [comment]
E um carregamento pode ter mais de uma NF ou pedido ou ordem de compra?

**Comment by angelitakoehler** [comment]
Rogerio,
Em um mesmo caminhão eu posso ter mais de uma NF, mas observe que a alimentação das informações  no carregamento são sempre por NF, inclusive toda a pesquisa e atribuição de status é por documento não por caminhão.
Esta é a forma que teremos de calcular o OTIF para cada cliente.

**Comment by engrogerio** [comment]
Da forma como está modelado hoje, o campo NF está tanto em Carregamento como em Pedidos, então usamos este campo para relacionar quais ítens são de quais carregamentos.

Se, em um caminhão podemos ter mais de uma NF, não faz mais sentido colocar NF como campo do carregamento, pois na lista de carregamentos apareceriam 1 para cada NF referentes a um único carregamento...Ex. Se um carregamento tem 4 NFs, apareceriam 4 linhas de carregamento, onde as 4 teriam que ser marcadas para alterar o status do carregamento...

Então, a NF deve ficar somente como campo do ítem do carregamento.

Mas aí a pergunta é: Como eu saberia quais NFs são relacionadas a um carregamento?

Pelos sistemas atuais, onde está a relação "Carregamento -> Pedidos" ?

**Comment by angelitakoehler** [comment]
Como tenho a impressão de que não estamos nos entendendo neste ítem, vou tentar esclarecer como pensamos as informações e então você poderá avaliar a melhor forma de apresentar isso.

Vou tentar esclarecer por aqui e se precisar esclarecer algo mais no detalhe, me acione no skype ou via fone.

Em nível de nota (onde cada nota refere-se a apenas um pedido):
  >> registrar em qual caminhão cada nota foi carregada
  >> Observações
  >> Confirmar o horário de grade do cliente.

Em nível de item de nota:
  >> Quantidade carregada de cada produto - por consequencia as faltas se houver
  >> Motivo da falta quando houver
  >> Quantidade de pallets do produto
  >> número de cada pallet (para as filiais que fazem este controle)
  
Em nível de caminhão (carregamento): 
  >> Transportadora
  >> Lacre
  >> Horário da chegada
  >> Horário do início do carregamento
  >> Horário de termino do carregamento
  >> Horário de liberação do caminhão


Com as informações acima, consiguiria extrair independente de do meu nível de análise (item/nota/caminhão):
	> status de chegada e liberação  (que será o mesmo para tudo que foi no caminhão)
	> observações registradas (que será a mesma para todos os itens da nota)

**Comment by engrogerio** [comment]
Pelo que vc descreveu 
* Em nível de caminhão (carregamento): A tela contempla todos os requisitos;
* Em nível de item de nota: Falta implementar os campos de numero de cada pallet
* Em nível de nota (onde cada nota refere-se a apenas um pedido):
Aqui está o X da questão.
Hoje está fixo em um carregamento por NF.
Você respondeu minha pergunta quando listou ai acima: registrar em qual caminhão cada nota foi carregada.
Então na tela inicial, em  vez de selecionar 1 NF para o carregamento, deve ser possível selecionar n NFs e o sistema deve entender que todas estas NFs irão no mesmo carregamento.
Talvez seja necessária uma outra tela para o carregamento.
Vou avaliar.
Pergunta: Como deveriam ser identificados os carregamentos? Nome do cliente + NFs ?

**Comment by angelitakoehler** [comment]
Na verdade no meu entendimento é por nota mesmo, da forma como está.
O que ocorre é que quando ele tem mais de uma nota no mesmo caminhão, ele vai informar os mesmos dados do caminhão/transportador/lacre em mais de uma nota.
Não sei se seria necessário uma tela para "carregamento", a menos que você crie na tela principal a possibilidade de marcar mais de um registro e uma opção de "registrar carregamento" onde abriria todas as notas, para registrar os dados do caminhão apenas uma vez, enfim.. pensa aí.. hehe
Mas não pode impedir que ele faça isto documento a documento, pois não sei como será a operação no dia a dia.
Depois de tudo registrado é importante que consigamos ter as informações por documento (nota/pedido/ordem carga), e item, pois será assim que isto será avaliado.

**Comment by engrogerio** [comment]
Perguntas:
Qual a porcentagem de carregamentos que levam mais de uma nf?
Um caminhão está programado para levar 2 nfs por exemplo, mas por algum motivo, leva somente 1 e é programado outro carregamento para levar a outra , ou seja, o carregamento é desmembrado. Isso pode ocorrer na prática?
Estou tentando encontrar alguma coisa que justifique deixar da forma como está ou criar uma hierarquia a mais. Hoje temos 2 níveis : Carregamento é pai de Itens.
3 Níveis seria: Carregamento é pai de Notas_Fiscais que é pai de Itens.

**Comment by angelitakoehler** [comment]
Não sei o % de cargas com mais de uma NF, mas temos um volume significativo deste tipo, nas fábricas de JDF e OSA.
Sim, se o caminhão está programado para levar 2 NFs e ocorre um problema, poderá levar apenas uma e outro caminhão irá levar a NF faltante, isto ocorre sim.
Na minha visão a Hierarquia deve ser:
Notas fiscais é pai de itens.
Dados do caminhão é informação complementar da NF.
Att

**Comment by engrogerio** [comment]
Ok. Somente acrescentados os campos de Pedido e Ordem em todas as telas.
Teste e encerre por favor.

**Comment by angelitakoehler** [comment]
Parece OK, vamos testar com a base oficial, onde teremos os números para o pedido e a ordem de compra.
