### ISSUE TITLE
Tela de No-Show precisa permitir consulta por mais campos

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#23]
Atualmente a tela de no-show está permitindo pesquisa apenas pelo nr da NF.
Permitir também por:
- Cliente
- Pedido
- Ordem de compra

**Comment by engrogerio** [comment]
ver #22

**Comment by engrogerio** [comment]
Ok. Permite consulta por Cliente, nf, pedido e ordem de compra.
Testar e encerrar.

**Comment by angelitakoehler** [comment]
ok
