### ISSUE TITLE
Visualização do status dos carregamentos

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#24]
Precisamos de uma tela para visualizar o status dos carregamentos, ou pode ser na própria tela do carregamento.

Precisa informar o status da chegada e o da liberação através das formulas como na planilha exemplo enviada.
Vide colunas W e X da pasta carregamentos da planilha enviada.

**Comment by angelitakoehler** [comment]
Rogerio, você designou este issue para mim, mas não entendi bem porque.
Notei que dentro da tela de carregamento aparece este status, mas neste caso é mandatório abrir cada nota para saber quando o que citei  nesta issue é que precisamos de uma forma simples de visualizar esta informação de todas as notas.
Acredito que a sua sugestão do call de termos uma forma de extrair os relatórios com todas as informações irá atender, se este status estiver disponível também para buscar.

**Comment by engrogerio** [comment]
Feito

**Comment by angelitakoehler** [comment]
OK
