### ISSUE TITLE
Criação de usuário não está funcionando

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#25]
Criei um usuário novo, para iniciar testes de perfil de acesso, porém não consegui realizar acesso com o usuário criado.
Tentei alterar a senha para ver se permitia o acesso, mas não permite mantém a mensagem de que o usuário ou a senha estão incorretos.
Estou escrevendo o usuário com maiúsculas e minúsculas corretamente e a senha também está certa, porém não acessa.

**Comment by engrogerio** [comment]
Deve ser marcada a caixa: "Membro da Equipe"

**Comment by angelitakoehler** [comment]
HUmm... Não marquei esta opção pois a descrição parecia ser algo que daria direito de administração.
Mas OK, fiz o teste e agora funciona.
