### ISSUE TITLE
Usuário não está respeitando permissões do Grupo Acesso

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#28]
Criei um usuário de teste e um grupo de acessos apenas para isto.
Supondo que será uma pessoa da expedição.
Este usuário deverá ter acesso a registrar os dados do carregamento e quantidades carregadas, mas não deverá ter acesso a mais nada.

O que observei:
- O usuário está com acesso a regitrar multas tanto de fill rate quanto de no-show.
- O usuário consegue efeturar os registros da tela inicial do carregamento (indicar que o caminhão chegou e o carregamento foi iniciado, por exemplo), mas não consegue abrir os detalhes da nota para informar placa, e quantidades carregadas, pois ocorre erro, parece ser um erro de falta de permissão.

**Comment by engrogerio** [comment]
Se você adicionar a permissão "View" de um objeto, quer dizer que o grupo vai ter somente permissão de visualização daquele objeto e não precisa adicionar nenhuma outra permissão.
Testa desta forma e informe o resultado.

**Comment by angelitakoehler** [comment]
Não entendi. Este grupo que eu criei simula as permissões da expedição de uma fábrica.
Para isto eu selecionei:
- Visualização e edição de tudo o que está relacionado com o carregamento
Não marquei:
- Nada que esteja relacionado a fill-rate pois estes usuários não poderão nem mesmo ver a tela de multas.
- Nada que esteja relacionado a no-show poisestes usuários não poderão nem mesmo ver a tela de multas.

No resultado:
está correto:
- Vê a tela de carregamento e consegue assinalar chegada de caminhã, e início de carregamento, mas só na tela de acesso principal.

está errado:
- Não consegue acessar o detalhe do carregamento de uma nota,  para informar placa e quantidade.
- Está vedo a tela de fill-rate - e consegue consultar os detalhes.
- Está vendo a tela de no-show - e consegue consultar os detalhes.

Utilize o usuário teste que eu criei  com a senha 1234 e você verá do que estou falando.

Att,

**Comment by engrogerio** [comment]
quanto a acessar o detalhe do carregamento, é só retirar a permissão "View" dos items de carregamento.

**Comment by angelitakoehler** [comment]
Estou incrivelmente surpresa com esta solução!!! pois ela é contra a lógica! rs
Mas funcionou!
O que ainda está pendente é as telas de multas, pois não inclui no perfil do usuário e ainda assim elas aparecem, não estão permitindo alteração, mas ainda permitem as consultas.

**Comment by engrogerio** [comment]
Corrigido. Testar e encerrar.

**Comment by angelitakoehler** [comment]
Agora está aparecendo apenas o carregamento para o meu usuário de teste.
Porém ele não consegue informar a quantidade carregada de cada item.

**Comment by engrogerio** [comment]
se você não está conseguindo entrar dados no ítem, é porque deve ter uma permissão "View" no item, o que torna ele somente leitura. É só retirar a permissão de view e colocar uma de Change.

**Comment by angelitakoehler** [comment]
ok
