### ISSUE TITLE
Eliminar botão para inserir manualmente um carregamento

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#3]
A tela de carregamento possui botão para inserir manualmente um carregamento, mas quando este é acionado, não permite informar os dados de forma completa, esta é uma funcionalidade que realmente não havia sido solicitada, pois eles devem alimentar apenas com dados de documentos existentes e vindos do ERP.

**Comment by engrogerio** [comment]
Vou retirar o botão de inserir carregamento. Realmente não faz sentido.

**Comment by angelitakoehler** [comment]
Ok, pode encerrar.
