### ISSUE TITLE
Não está permitindo cadastrar multa - perfil de teste

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#33]
Criei um perfil que simule o acesso da área comercial, que deveria ter permissão apenas para:
> visualizar as multas
> incluir multas de fill rate e de no-show
> todos os estabelecimentos

Porém, quando acesso com o usuário que está com este perfil, ele consegue visualizar as notas mas não consegue incluir valor de multa.

**Comment by engrogerio** [comment]
Se em qualquer tela não é possível entrar algum valor, é que está selecionado para o usuário ou grupo a opção "Can View" que sobrescreve a "Can Change".
Neste caso é só excluir a "Can View Multa Item" (Fill Rate) e a "Can View Multa Carregamento" (No show)

**Comment by angelitakoehler** [comment]
ok
