### ISSUE TITLE
Não salva valor no Fill Rate

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#34]
Criei um perfil de teste que pode incluir multas.

No fill rate está permitindo informar valores tanto o valor base quanto o valo multa.
Porém quando salvo, o valor da multa não fica registrado, ele é perdido.

O valor base salva corretamente.

**Comment by engrogerio** [comment]
a formula é multa=valor base * qtd itens faltantes. Se itens faltantes =0, multa =0

**Comment by angelitakoehler** [comment]
Rogerio,
Não sei se você lembra do email que eu te mandei no dia 12/12/16 com as definições sobre as multas.
Neste email, citei que depois das últimas conversas com o usuário, o melhor seria mesmo no fill rate, deixar que seja informado a multa na mão.
Isto porque lembra que comentei que pode não ter a menção de falta no nosso carregamento, mas o cliente pode acusar a falta na entrega.

**Comment by engrogerio** [comment]
**No Show** - este é um tipo de multa, aplicada quando a Aryzta não entrega o pedido inteiro, ou perde a data/hora do agendamento de entrega, neste caso ocorrem as seguintes penalidades:
o   Alguns varejos cobram um valor fixo pelo "no show"  - previsto armazenar a informação no campo "VL_FIXO" da tabela "ARZ_BASE_OTIF" – ET. Este valor pode ser "0" zero para algum varejo que não adote esta politica;
o   Além do valor fixo, também existem as penalidades em % sobre o valor do pedido não entregue, para isto havia sido previsto dois campos na tabela "ARZ_BASE_OTIF", "VL_BASE e VL_MULTA", pois originalmente havíamos previsto realizar a multiplicação do valor do pedido pelo valor base que conteria o % da multa, porém como o valor geralmente é sobre o pedido original do cliente, que pode não corresponder ao nosso pedido, acho que o mais adequado seja **deixar apenas o campo "VL_MULTA" e o comercial digitará o valor já calculado.**
**Fill Rate** – este é um tipo de multa que é aplicado quando a Aryzta, entrega o pedido de forma incompleta, a penalidade é:
o   Um % sobre o valor da mercadoria não entregue, para este caso também havia sido previsto campos na tabela "ARZ_BASE_OTIF_ITEM" , sendo "VL_BASE e VL_MULTA", pois havia previsto calcular o valor da multa, mas também neste caso os valores nem sempre são os que constam em nosso pedido/NF, pois alguns clientes usam como base valor bruto e outros valor liquido, desta forma entendo que o melhor é **deixar apenas o campo "VL_MULTA" e estes valores serem digitados pelo comercial já calculados.**

**Comment by engrogerio** [comment]
Implementado.

**Comment by angelitakoehler** [comment]
Ok
