### ISSUE TITLE
No Show não permite incluir multa

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#35]
Criei um perfil de teste que permite incluir multas.
Não possui o acesso de "View", mas possui todos os outros 3.

Aina assim, não abre o campo pra informar o valor da multa.
Também não mostra o que esta cadastrado quando abro uma nota que já tem multa registrada.

**Comment by engrogerio** [comment]
qual o usuario / senha ?

**Comment by angelitakoehler** [comment]
testecomfl/123

**Comment by engrogerio** [comment]
tava faltando a permissão de Multa / Carregamento. Adicionei e funcionou.

**Comment by angelitakoehler** [comment]
Agora esta abrindo, salva o valor fixo da multa, porém não salva o valor da multa.

**Comment by engrogerio** [comment]
Corrigido.

**Comment by angelitakoehler** [comment]
OK
