### ISSUE TITLE
Log de alterações

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#38]
O log não está gravando os valores alterados, apenas informa que foi alterado, se for necessário verificar quem alterou para qual valor não vamos conseguir e este é o objetivo.
Além disto, observei que quando marcamos a chegada do caminhão ou o início do carregamento, pela tela inicial, isto não vai para o log.

**Comment by engrogerio** [comment]
1- O log grava as alterações executadas. O valor alterado está no registro atual.
2- O registro dos carregamentos no log foi corrigido e estará disponĩvel quando fizermos a atualização no seu servidor.
