### ISSUE TITLE
Tela de cadastro da grade

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#39]
No cadastro da grade seria interessante ter uma indicação do horário e um marcador para os dias da semana, porque temos clientes que carregam de segunda a sábado, por exemplo no mesmo horário todos os dias.

**Comment by engrogerio** [comment]
Não entendi. O que é indicação de horário? O que é um marcador?
Você tem as grades em algum sistema ou planilha? Podemos fazer um upload manual para o db.

**Comment by derikf** [comment]
Rogério,

Referente a este caso, sim, temos essa lista de grade e pretendo inserir via banco diretamente. Já solicitei esta lista para o Comercial (DAC), e estou aguardando um retorno para fazermos esse upload.

**Comment by derikf** [comment]
@engrogerio 
Já recebi a lista das grades dos clientes. Estou fazendo uma tratativa no arquivo para facilitar o upload de informações.

**Comment by derikf** [comment]
@engrogerio 
Apenas anexando a grade dos clientes.

Ainda estou pensando em uma melhor forma de inserir estas grades, pois teremos que cadastrar todos os clientes e seus respectivos horários para todos os dias da semana, exceto domingo.

Edit: aceito sugestões também.

[Bloco K - Rev. 05Jun17.xlsx](https://github.com/engrogerio/sgo/files/1059317/Bloco.K.-.Rev.05Jun17.xlsx)

**Comment by derikf** [comment]
@engrogerio 
Referente ao seu comentário, se criar esta tabela com "Cliente x horário" ficaria mais fácil para alimentar as grades ? Pois veja que na planilha, os clientes estão agrupados.
Por exemplo: Outback - Carregamento 06:00, ou seja, todas as lojas (siglas) do Outback serão às 06:00.

Precisamos alinhar a questão de quais clientes fazem parte de tal grupo.

**Comment by engrogerio** [comment]
Tenho que criar um script para inserir conforme o anexo, adicionando 7 registros para cada linha desse anexo, pois de acordo com os requisitos enviados, a grade é relativa a um dia da semana.
[listagem grades.xlsx](https://github.com/engrogerio/sgo/files/1062769/listagem.grades.xlsx)

**Comment by derikf** [comment]
@engrogerio 
Boa tarde.
Como está este caso ? Conseguiu criar o script ?

**Comment by engrogerio** [comment]
por favor, confirme se todos os clientes e horários que devem estar na grade, estão na planilha do comentário... 
Nessa lista não tem restrição de dias de semana? Todos horários são de segunda a sábado?

**Comment by derikf** [comment]
Bom dia Rogério,

Pelo que você enviou, os clientes estão agrupados pelo Código de Grupo de Clientes ou “Canal”, se eu entendi direito. Mas no sistema não está assim.

Encontrei 2 bons exemplos:
![1](https://user-images.githubusercontent.com/27302062/27432093-2cd50142-5725-11e7-95bf-d8f1ed99a84c.png)

- GRP (MB) temos diversas lojas ( ou códigos de clientes ) que compõem este “grupo GRP”;
- Outback na sua planilha está resumido em 3 grupos, mas no sistema está assim:
![2](https://user-images.githubusercontent.com/27302062/27432111-3cfe9420-5725-11e7-86d5-6e8587651853.png)

Ou seja, todas as lojas do Outback que estão no “Grupo Outback” estão agrupados de uma forma geral, só que no sistema, estes clientes estão separados por “loja a loja”.
Como você saberá qual horário colocar em qual cliente ? Esta amarração de Grupo x Cliente consta no banco de dados?

Desculpe a demora no retorno, mas está complicado aqui esses dias.

Obrigado,

**Comment by engrogerio** [comment]
Pergunta. Quando o usuário escolhe um cliente para fazer um carregamento, ele escolhe sempre um cliente unitário ou escolhe um grupo?
Não existe no sistema uma entidade 'Grupo de Clientes', então a tabela de grades deve ser sempre para um cliente específico, e não um grupo.
Funcionaria dessa forma?

**Comment by derikf** [comment]
Ele escolhe sempre um ou mais clientes(lojas) por vez, mas nunca um grupo inteiro. Pois mesmo sendo grupo de cliente, cada cliente (loja) tem seu horário de carregamento.

Não funcionaria em grupo ao meu ver, justamente pelo que comentei acima, mesmo sendo grupo de cliente, cada um tem seu horário.

Em anexo, envio um arquivo contendo todas as lojas que fazem parte do grupo "GRP" que consta na lista que você enviou, com o código delas no nosso sistema interno e com a sigla (nome abreviado) que consta no sistema de OTIF.
Ou seja, todas essas lojas, devem ter horários de carregamento preenchidos no sistema para às 05:00hs, 13:00hs e 20:00hs, todos os dias.

Se este arquivo te ajudar a fazer os inserts, procuro fazer o mesmo com os demais clientes.

Obrigado.

[Lojas GRP.xlsx](https://github.com/engrogerio/sgo/files/1108629/Lojas.GRP.xlsx)

**Comment by engrogerio** [comment]
Para eu criar um script aqui, pode fazer o mesmo com os outros clientes, mas falta indicar a que unidades aplicam cada janela de cada cliente.
Anexo um exemplo de como vai ficar a tabela com o que vc enviou aí em cima somente para JDF e com os outros clientes que eu tinha a janela.
[listagem grades.xlsx](https://github.com/engrogerio/sgo/files/1110586/listagem.grades.xlsx)

**Comment by derikf** [comment]
Vou montar um lista melhor e te passo.

**Comment by derikf** [comment]
Em anexo envio a lista da lojas e horários somente de OSASCO, código da empresa é 03.
Lembrando que estes horários são para todos os dias da semana, exceto domingos.

[Lojas e Grades OSA.xlsx](https://github.com/engrogerio/sgo/files/1120421/Lojas.e.Grades.OSA.xlsx)

**Comment by derikf** [comment]
Agora envio a lista da lojas e horários somente de Juiz De Fora, código da empresa é 02.
Lembrando que estes horários são para todos os dias da semana, exceto domingos.

[Lojas e Grades JDF.xlsx](https://github.com/engrogerio/sgo/files/1120424/Lojas.e.Grades.JDF.xlsx)

**Comment by derikf** [comment]
Quando eu finalizar a lista de Jaguariuna, eu envio.

**Comment by derikf** [comment]
@engrogerio 
Em anexo envio a lista de lojas e horários somente de Jaguariuna, código da empresa 08.
Lembrando que estes horários são para todos os dias da semana, exceto domingos.

[Lojas e Grades JAG.xlsx](https://github.com/engrogerio/sgo/files/1142955/Lojas.e.Grades.JAG.xlsx)

**Comment by engrogerio** [comment]
Ainda falta STO.
Vou elaborar o script para preencher a tabela de Grades.
Preciso dos IDs das Unidades como ficou no db. Por favor, confirme se são esses:
JDF = 2
OSA = 3
STO = 
JAG = 8

**Comment by derikf** [comment]
Referente STO, não tem grade, ou pelo menos, não me passaram grade nenhuma.

O ID das unidades está correto. STO é 04.

**Comment by engrogerio** [comment]
Esse número é realmente o campo id da tabela? O id é um inteiro então não
tem o zero na frente ...

Em 24 de jul de 2017 1:04 PM, "derikf" <notifications@github.com> escreveu:

**Comment by derikf** [comment]
Segue ID da tabela: business_unit_businessunit

![image](https://user-images.githubusercontent.com/27302062/28585279-3383f634-7146-11e7-8023-220ba91ed0f0.png)

**Comment by engrogerio** [comment]
Preciso de uma planilha  com os campos id e nm_ab_cli da tabela cliente_cliente para finalizar o script.
Vou enviar um sql com 9180 inserts.

**Comment by derikf** [comment]
Segue anexo conforme solicitado.

[ID e nome Clientes.xlsx](https://github.com/engrogerio/sgo/files/1176425/ID.e.nome.Clientes.xlsx)

**Comment by engrogerio** [comment]
Há cerca de 80 clientes que existem nas grades, mas não vieram na planilha de clientes:
Gero o script para adicionar as grades excluindo estes clientes, ou você pode reenviar a planilha de clientes com os IDs destes ?

BFOOD
BRFSP
CDPR
FFDF
FFSP
GIRAFFAS
LADBK
GIRAFFAS SP
KFC-BRE
KFC-CPN
KFC-MOO
KFC-SCS
KFC-APV
KFC-CEN
KFC-TIJ
KFC-LMA
KFC-BOT
KFC-NSH
KFC-MAD
KFC-STA
KFC-DQC
KFC-IPA
KFC-OSC
KFC-GRL
KFC-VMA
KFC-OSU
KFC-SET
KFC-MAC
KFC-SBC
CATIARA
KFC-SST
KFC-BCG
KFC-SEL
CVLFD
CVLBR
FIORZ
SELVA
CATAR
FRERS
SOSAL
MASSA
JGBSP
OBDEP
OBMOB
OBRPT
OBSJC
OBBH1
OBREC
OBRSH
OBBSB
OBBS2
OBFLN
OBCR2
OBGOI
OBPOA
OBSBS
OBCRT
OBP21
OBSJR
OBVSH
OBVEL
OBMCZ
OBCGD
OBGPA
OBUBR
OBBHB
OBBHS
OBFRM
OBNAT
OBLDA
OBSIG
OBSI2
ABSVO
OBFIG
OBBCB
OBCAM
ABCPS
OBGO3
CARIOCARGO
OBVEN
OBACL
MASSA

**Comment by derikf** [comment]
Consultando na tabela cliente_cliente do OTIF, esses clientes não constam lá, então não tenho o ID deles nesta tabela.
Consultando no nosso sistema aqui, eu encontrei o código deles. 
Se não te servir, gera sem esses clientes mesmo. Precisamos colocar essas grades no sistema.

[Clientes faltantes.xlsx](https://github.com/engrogerio/sgo/files/1178243/Clientes.faltantes.xlsx)

**Comment by engrogerio** [comment]
Segue os inserts de grades para os clientes que já existem na tabela cliente_cliente.
quando tiver os ids dos outros clientes, informe para eu gerar os inserts faltantes.
[insert_grades.xlsx](https://github.com/engrogerio/sgo/files/1178361/insert_grades.xlsx)

**Comment by derikf** [comment]
Por favor, me envie a planilha consolidada de onde foi originado esses inserts, preciso fazer uns ajustes.
Porque no campo de horário desta tabela grade_grade, você definiu este campo como "timestamp" e esse formato é um pouco chato para fazer insert, pois somente enviando o horário naquele campo, ele não aceitou:

![image](https://user-images.githubusercontent.com/27302062/28667803-6d125162-72a3-11e7-82f5-8a3328a9f9b4.png)

Ou, se preferir, ajuste o horário na planilha de acordo com o formato do timestamp:

![image](https://user-images.githubusercontent.com/27302062/28667824-850fb6ce-72a3-11e7-8c43-139eab151ad6.png)

**Comment by engrogerio** [comment]
Se você fizer um insert na mão para testar com '01-JAN-00 05:00 PM' ele funciona?
Por favor, teste o insert e a funcionalidade do sistema usando essa grade.

**Comment by engrogerio** [comment]
Se você fizer um insert na mão para testar com '01-JAN-00 05:00 PM' ele funciona?
Por favor, teste o insert e a funcionalidade do sistema usando essa grade.
Ou mudamos de estratégia conforme esta resposta:
https://dba.stackexchange.com/questions/42084/most-efficient-and-practical-way-to-store-time-values-hhmm-in-oracle-that-mak

**Comment by derikf** [comment]
Inseri esta data diretamente no insert e não deu certo:

![image](https://user-images.githubusercontent.com/27302062/28673785-dd1ff4f8-72b9-11e7-989e-474d1b73523d.png)

**Comment by engrogerio** [comment]
Então tenta '01-01-00 05:00 PM'

**Comment by derikf** [comment]
Não funciona, pois Oracle não aceita mês em numérico, só abreviado em inglês... JAN, FEB, etc.

**Comment by engrogerio** [comment]
Por favor, teste com '01-JAN-2000 5:00:00'

**Comment by derikf** [comment]
Agora sim!

![image](https://user-images.githubusercontent.com/27302062/28716202-31912102-7372-11e7-8a40-06d0fc93d6d4.png)

**Comment by derikf** [comment]
Por favor, gere uma nova planilha com este formato de insert, que deu certo.

**Comment by engrogerio** [comment]
Por favor, verifique se a funcionalidade do sistema está ok com esse novo
registro.

Em 28 de jul de 2017 8:53 AM, "derikf" <notifications@github.com> escreveu:

**Comment by derikf** [comment]
Sim, está funcional. Foi registrado corretamente.

**Comment by engrogerio** [comment]
1- Na tela de carregamento, teste se aparece o horário do campo "Grade do Cliente" aparece no campo "Horário" quando você salva o registro. 
2- Na mesma tela, verifique se o status de chegada está sendo calculado corretamente baseado no horário da grade.
Vou trabalhar na geração dos inserts novamente.

**Comment by derikf** [comment]
1 - Campo horário aparece, porém, a Grade do Cliente não;

![image](https://user-images.githubusercontent.com/27302062/28729668-9f492f56-73a3-11e7-8c79-0b6e99cdb040.png)

2 - Sim, está sendo calculado.

**Comment by engrogerio** [comment]
Você inseriu uma grade para o cliente de ID 1749 para a Fabrica de ID 41 para segunda feira (0). Se você entrar em um pedido deste cliente e selecionar uma data que seja segunda-feira, vai aparecer esse horário no campo grade do cliente. Pode testar por favor?

**Comment by engrogerio** [comment]
acredito que a aplicação hoje, não está distinguindo grades de cliente por planta... Se você confirmar, por favor, abra um issue novo para isso.

**Comment by engrogerio** [comment]
Segue script corrigido.
[insert_grades.xlsx](https://github.com/engrogerio/sgo/files/1184376/insert_grades.xlsx)

**Comment by derikf** [comment]
Quando fui inserir os inserts novos, está dando erro quando o horário passa de 12hs (meio-dia).

![image](https://user-images.githubusercontent.com/27302062/28783599-3923c5e2-75e7-11e7-99ff-1f1edb709abe.png)

Ao consultar a estrutura da tabela, porque você usou o tipo campo de "Hora Grade" como TIMESTAMP ? Tipo DATE não serviria ?

![image](https://user-images.githubusercontent.com/27302062/28783555-14f96d48-75e7-11e7-9ece-4a56acc6f7d6.png)

**Comment by engrogerio** [comment]
DATE não tem horário. Estou fazendo uns testes com TIMESTAMP, mas se não funcionar, talvez tenhamos que ter 1 campo para hora e outro para minutos.

**Comment by engrogerio** [comment]
For getting only time part:
SELECT TO_CHAR(DATE_COLUMN,'HH24:MI:SS') from TABLE;

**Comment by derikf** [comment]
Entendemos como funciona esse TIMESTAMP e já realizamos as modificações.
Inserts inseridos.
