### ISSUE TITLE
hora da grade do cliente deveria trazer de acordo com o que está cadastrado

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#4]
Na tela de carregamento, a hora da grade do cliente deveria trazer de acordo com o que está cadastrado e não ser informado

**Comment by engrogerio** [comment]
Para cadastrar o horário da grade, basta selecionar o horário no campo "grade do cliente" e salvar. O horário vai ser salvo no campo "Horário Programado". Isso atende? Posso fechar este issue?

**Comment by angelitakoehler** [comment]
Não, se eu tenho uma grade cadastrada para este cliente neste estabelecimento obrigatoriamente tem que trazer o que está cadastrado para ele para aquele dia, não pode permitir que seja escolhido, isto é fixo, para isto serve o cadastro.
Novamente, acho que uma conversa por fone esclareceria estes pontos.

**Comment by engrogerio** [comment]
Dado um estabelecimento , um cliente e um dia da semana, só pode existir 1 horário de grade?

**Comment by angelitakoehler** [comment]
Rogerio,
Confirmei este ponto com a usuária, e na verdade pode ter mais de um horário no mesmo dia para o cliente, então não vai funcionar assumir fixo, vai ter que permitir escolher mesmo.
Porém, observe que na lista somente pode mostrar as grades daquele estabelecimento/cliente/dia.

**Comment by engrogerio** [comment]
Ok. Está funcionando. Só preciso melhorar a tela de cadastro de grades para ficar mais intuitiva.

**Comment by angelitakoehler** [comment]
No carregamento está OK, pode encerrar.
