### ISSUE TITLE
Erro tabela pedido_carregamento

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#41]
@engrogerio 
Quando vou executar a carga para atualização de informações na base testes, me acusa o erro em anexo (erro banco).
![erro banco](https://cloud.githubusercontent.com/assets/27302062/26699530/a3063de4-46f0-11e7-8cf5-1264440d3822.png)

Além disto, verifiquei que na tabela “pedido.carramento”, existem 2 campos de PALLETS, e o código está reclamando que não pode inserir NULL no campo mencionado em anexo (erro banco 1).
![erro banco 1](https://cloud.githubusercontent.com/assets/27302062/26700016/3598b50a-46f2-11e7-90e1-f15b90a1a9a1.png)

Como corrigir estes casos ?

Pergunto pois verifiquei que na base de produção, este novo campo “qt_pallet” ainda não consta na tabela e lá, eu criei uma procedure para ficar executando este insert de informações e está funcionando perfeitamente. 
Então, gostaria que quando este campo fosse inserido na base de produção, este problema já tenha sido resolvido.

Obrigado.

**Comment by engrogerio** [comment]
https://stackoverflow.com/questions/5199849/split-varchar-into-separate-columns-in-oracle

**Comment by derikf** [comment]
Acho que não tem relação com o problema em questão.

**Comment by engrogerio** [comment]
Esse campo precisa que o script insira 0 sempre. Realmente ele não pode ficar vazio pois o sistema usa ele para abrir os campos para digitar os numeros de pallets.

**Comment by derikf** [comment]
@engrogerio 
Resolvi. 
Acrescentei o 0 (zero) no insert que você criou. Agora este campo "QT_PALLET" sempre vai receber zero, conforme falado.
