### ISSUE TITLE
Disponibilizar Queries na produção.

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#42]
@engrogerio 
Gostaria que fosse disponibilizado a opção "Queries" na base de Produção.

![image](https://cloud.githubusercontent.com/assets/27302062/26700135/a10e39c2-46f2-11e7-9e7a-e84e48e6eeed.png)

Obrigado.

**Comment by engrogerio** [comment]
Acho que você quis dizer na base de teste , né?

**Comment by derikf** [comment]
@engrogerio 
Não, base de produção mesmo, pois na base de testes já foi disponibilizado e já criei uns relatórios simples para testes.

**Comment by engrogerio** [comment]
Ok. Feito. Aguardando a liberação do TeamViewer para atualizar ambos os servidores.

**Comment by derikf** [comment]
@engrogerio 
Após atualização e migrate da base de produção, o Query é exibido em tela, porém comparando com a base de teste, as tabelas "explorer_query" e "explorer_querylog" não constam no banco:

![image](https://user-images.githubusercontent.com/27302062/26901539-97c0d186-4bac-11e7-8e20-e1e1eb06194f.png)

**Comment by derikf** [comment]
Agora está funcionando.
