### ISSUE TITLE
Novo filtro na tela de Carregamento

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#43]
@engrogerio 
Gostaria que fosse criado um novo filtro na tela de Carregamentos. Seria um filtro de datas, buscando do campo "Datas Programadas" desta mesma tela.
![image](https://cloud.githubusercontent.com/assets/27302062/26700503/fa8c4308-46f3-11e7-8d5f-83433e739089.png)

**Comment by engrogerio** [comment]
Se você clicar no título da tabela (Data Programada) ele classifica tudo por essa data. Isso não é suficiente?
Se colocarmos filtro por data programada como você pede, teríamos que definir os títulos do filtro. Ex:
Semana atual
Semana passada
Mês passado
Mes atual
...
Alguma ideia de como deveria ser a tela desse filtro?

**Comment by derikf** [comment]
@engrogerio 
Não é suficiente, pois pelo que vi, só classifica a data de 2 formas, menor e maior.
Pode manter estes filtros mencionados acima, e se possível, acrescentar uma seleção de datas. Ex: Período de xx/xx/xxxx até xx/xx/xxxx.

Não preciso de nova tela, apenas disponibilizar no menu ao lado mesmo (linhas em azul, apenas para referenciar o local):

![image](https://cloud.githubusercontent.com/assets/27302062/26784366/92bd73e0-49d3-11e7-94cf-4c9e80260c6a.png)

**Comment by engrogerio** [comment]
Ainda insistindo nesse issue... Você precisa de alguma configuração inicial?
Por exemplo: 
"toda vez que o usuário acessar essa tela de listagem de pedidos, deve estar automáticamente filtrado para mostrar somente os carregamentos iniciados no mês atual"

**Comment by derikf** [comment]
Não precisa. O jeito que a tela já exibe hoje está atendendo muito bem.

**Comment by engrogerio** [comment]
Ficou desta forma. Posso fazer?
![image](https://cloud.githubusercontent.com/assets/6229885/26834427/af70b546-4aab-11e7-86b1-a5e9964d83e9.png)

**Comment by derikf** [comment]
Sim! Pode fazer. Ficou bom assim.

**Comment by derikf** [comment]
Apenas para informar que estou sem Skype devido a troca de domínio da empresa. 
Te enviei um e-mail perguntando se pode atualizar os ambientes hoje, às 18hs.

**Comment by derikf** [comment]
@engrogerio 
Favor trocar o label do botão "Reset" para "Limpar":

![image](https://user-images.githubusercontent.com/27302062/26853495-9d9fc5cc-4ae8-11e7-9a52-cabff9c45026.png)

**Comment by engrogerio** [comment]
~/.virtualenvs/invent186_py2/lib/python2.7/site-packages/rangefilter/templates/rangefilter/date_filter.html
line 30

**Comment by derikf** [comment]
Não entendi. Seria algum link ?

**Comment by engrogerio** [comment]
Implementado.
