### ISSUE TITLE
Canal de Cliente

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#44]
@engrogerio 
Vi que na view criada pela Angelita, utilizada para buscar as informações do Totvs, umas destas informações é o “Canal de Cliente”. Gostaríamos que esta informação fosse carregada para o OTIF e que também fosse apresentada em uma coluna na tela de Carregamentos, para facilitar o trabalho dos envolvidos e também na geração de relatórios:
![image](https://cloud.githubusercontent.com/assets/27302062/26700937/9959539e-46f5-11e7-9f55-dcdcaea1cb94.png)

Obrigado.

**Comment by engrogerio** [comment]
Esse campo já existe no DB: Se chama 'ds_classe_cli' e está na tabela 'cliente_cliente'. Temos que alterar o script. Assim está ok?
![image](https://cloud.githubusercontent.com/assets/6229885/26824707/cbaca2ba-4a88-11e7-8dbd-759f407b69bc.png)

**Comment by derikf** [comment]
Entendi. 
Sim, assim está perfeito. Pode alterar.

**Comment by engrogerio** [comment]
Ok. Feito. Aguardando a liberação do TeamViewer para atualizar ambos os servidores.
