### ISSUE TITLE
Apontamentos retroativos

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#45]
@engrogerio 
Além da forma de apontamentos dos carregamentos como é feito atualmente – buscando informação de data e hora diretamente “do Windows” através da ação executada em tela – precisamos de uma forma para realizar lançamentos retroativos manualmente no sistema para casos de queda de energia e/ou rede ou outros problemas que possam ocorrer. 

Obrigado.

**Comment by engrogerio** [comment]
Ok. Feito. Aguardando a liberação do TeamViewer para atualizar ambos os servidores.
