### ISSUE TITLE
Novo filtro - Transportador

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#47]
@engrogerio 
Por favor, precisamos de um novo filtro na tela de Carregamentos.
Filtro por Transportadora - para que seja possível selecionar as transportadoras disponíveis.
Sugestão de local em anexo.

![transportadora](https://user-images.githubusercontent.com/27302062/28315123-91642502-6b93-11e7-9882-2abe098c704e.PNG)

**Comment by engrogerio** [comment]
Implementado. Aguardando acesso para deploy em produção.

**Comment by derikf** [comment]
Pode ser hoje mesmo ou na quarta-feira.
Me informe o melhor horário para você após às 17hs.
