### ISSUE TITLE
Horário carregamento

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#48]
@engrogerio 
Qual a possibilidade de colocar o "bloco" para realizar os apontamentos dos horários manualmente para mais de um carregamento ao mesmo tempo?

Algo parecido com o print em anexo. Ao selecionar mais de um Carregamento, abaixo das linhas dos Carregamentos, informar o mesmo horário para todos os Carregamentos selecionados.

![print1](https://user-images.githubusercontent.com/27302062/28335195-f8041ade-6bd3-11e7-84b6-d3f7fb3e027a.PNG)

Edit: um detalhe importante. Não é para remover este "bloco" dos horários de dentro do Carregamento, seria apenas uma cópia para este novo local, com as mesmas regras e fucnionalidades.

**Comment by engrogerio** [comment]
Entendi.
Vai funcionar assim:
1- Seleciona vários carregamentos e escolhe por exemplo a opção : "Alterar Horário de chegada do caminhão"
2- O sistema irá exibir uma tela para digitar a nova data.
3- O sistema irá alterar as datas de chegada dos carregamentos selecionados.
Você concorda com esse fluxo?

**Comment by derikf** [comment]
Isso, pode ser desta forma, acho que fica melhor aparecendo uma tela.
Se possível, esta tela que for aparecer, seja igual a que informamos as datas e horários, para não criar problema para quem for utilizar o sistema.

![capturar](https://user-images.githubusercontent.com/27302062/28338174-77929974-6bde-11e7-9efd-13d0d0f48280.PNG)

Vou informar a responsável por esta solicitação, se ela concorda para que apareça esta tela.

**Comment by derikf** [comment]
@engrogerio pode dar sequência neste caso.

Pode fazer com que, após selecionar múltiplos carregamentos, seja exibida uma janela para informar os horários para todos os carregamentos selecionados.
Além disso, precisamos que nesta mesma janela, seja possível informar também os campos: 
"Placa do veículo" e "Número Lacre":

![image](https://user-images.githubusercontent.com/27302062/28878027-75654b46-7774-11e7-8092-28a5599e0135.png)

**Comment by engrogerio** [comment]
Dúvidas:
1- Pedir a placa do veículo e numero do lacre só para o evento de chegada do caminhão na planta ou para todos os eventos?
2- Continua possível a alteração manual de horários na tela de acompanhamento de um carregamento específico? Se já existe um horário no campo, sobrescrever?
3- A data e horário programados são atualizados quando estão vazios e alguêm sinaliza a chegada do caminhão? E quando alguem sinaliza a liberação?

**Comment by derikf** [comment]
Bom dia.

1- Pedir esses dados na saída do caminhão. Pois durante o carregamente, pode ser que ocorra mudanças de caminhão e também, o número do lacre, só sabemos qual será após carregamento finalizado.

2- Sim, é melhor deixar possível alterar; Sim, sobrescrever.

3- A data programada já é exibida automaticamente e se não me engano, sim, o horário é mostrado quando a ação é executada; Quando é sinalizada a liberação, tem que ser validado se houve atraso, saiu no prazo correto, etc...

**Comment by engrogerio** [comment]
O sistema precisa que seja digitada a placa na entrada no caminhão, pois é a única forma de identificar quem está carregando o que. Pelo menos eu  acho...
O lacre pode ser na saída.
O problema é que, acho, tem que ser em tempos diferentes e não na mesma tela. Teoricamente, ele traria campos em branco, então se tem 2 campos e vc entra informação só em 1, o outro apaga o valor que estava gravado, pois está em branco. Ou podemos considerar que campo em branco é para não alterar a informação ja gravada...

**Comment by derikf** [comment]
Então deixa assim, com a necessidade de digitar a placa na entrada.

**Comment by engrogerio** [comment]
E o  lacre na saida?

**Comment by derikf** [comment]
Isso. Na saída.

**Comment by engrogerio** [comment]
Derik.
A versão final mostra os campos para entrar a data, o lacre e a placa sempre.
Se o campo ficar em branco, não é atualizado.
Vou disponibilizar uma versão de testes na nuvem.
