### ISSUE TITLE
Nova coluna - Tela Carregamentos

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#49]
Rogério,

Precisamos de uma nova coluna na tela de Carregamentos. 

Esta coluna deve ter o nome: **Rotas** e vai exibir informações do campo "cond_redespa", que buscamos do Totvs em nossa View:

![image](https://user-images.githubusercontent.com/27302062/28877560-2346140e-7773-11e7-96d8-3be65c113574.png)

Após você aalterar esta tela de Carregamentos, nós vamos ajustar também o comando "insert" que utilizamos para alimentar o OTIF.

Obrigado,

**Comment by engrogerio** [comment]
Me explique melhor esse campo. O que é uma rota? Tem algum exemplo de preenchimento?
Vamos cadastrar uma rota para cada carregamento?
O campo "Rota" pode ir abaixo do campo de observação do carregamento?

**Comment by derikf** [comment]
Rota é um agrupamento de clientes que serão atendidos pelo mesmo caminhão ou pela mesma rota de envio de mercadorias.

Não terá necessidade de cadastrar uma rota para cada Carregamento, pois esta informação nós já buscamos na View, este "vínculo" já vem pronto:

![image](https://user-images.githubusercontent.com/27302062/29031022-3fe38440-7b63-11e7-8aa2-3edd18be831f.png)

- Sim, pode ser abaixo do campo observação ou do lado deste na imagem abaixo, o que for mais fácil:

![image](https://user-images.githubusercontent.com/27302062/29031072-6c5e12c4-7b63-11e7-9c22-cae0e6c71deb.png)

Por favor, coloque em negrito também para destacar este campo, como é feito no campo "Quantidade de Pallets".

**Comment by engrogerio** [comment]
O campo Rota deve ser somente leitura ? O negrito é somente para campos que necessitam preenchimento pelo usuário.

**Comment by derikf** [comment]
Ah entendi.
Sim, é somente leitura.
