### ISSUE TITLE
Tela de carregamento  - campo "No Show"

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#5]
Existe um campo na tela "No Show" que está permitindo alterar -  não entendi a finalidade deste campo

**Comment by engrogerio** [comment]
A especificação que eu tenho é que o campo "No Show" deve ter um dos 2 valores: "S" ou "N". Por favor, explique como deve ser implementado.

**Comment by angelitakoehler** [comment]
Sim, na especificação que você tem - na tela de CADASTRAMENTO DAS MULTAS POR NO SHOW está solicitando informar S/N, na tela da expedição (carregamento) isto não é solicitado nem informado.
Portanto não sei para que serve nesta tela, pois não solicitamos.
Estou achando que você não entendeu o processo que será controlado neste sistema, se quiser, marcamos um call para que eu possa te esclarecer.

**Comment by engrogerio** [comment]
Por favor, me explique em que tela deveria ir este campo.

**Comment by angelitakoehler** [comment]
Este campo deverá estar na tela de cadastramento das multas por no-show.
Reforço que precisamos de um call pois você não esta entendendo a finalidade.

**Comment by angelitakoehler** [comment]
Ok, na tela de carregamento o campo não aparece mais.
Porém também não consigo ver nada na tela de inclusão de multas por No-Show

**Comment by engrogerio** [comment]
A lista inicial da tela de No-Show deve ter o mesmo comportamento da tela de Fill-Rate? Ou seja , inicialmente aparece somente os carregamentos que já tem multa, porém deve permitir busca por NF e permitir a inclusão de multas?

**Comment by angelitakoehler** [comment]
Na tela de carregamento o campo não aparece mais.
