### ISSUE TITLE
Novo filtro - Tela de Carregamentos

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#50]
Rogério,

Após inserir o novo campo "Rotas" na tela de Carregamentos, precisamos que seja acrescentado um novo filtro nesta mesma tela, que é "Filtro por Rotas", onde deve ser possível escolher as rotas que quisermos na tela de Carregamentos.

Pode seguir o mesmo padrão e local dos outros filtros já solicitados.

**Comment by engrogerio** [comment]
Implementado.
