### ISSUE TITLE
Parâmetro - Sugestão de Quantidade

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#51]
Precisamos da criação de um novo Parâmetro no sistema.
Neste parâmetro, precisamos informar um ou mais códigos de Grupos de Clientes que terão suas quantidades carregadas automaticamente para os respectivos Carregamentos.

Nós sugerimos o nome "Sugestão de Quantidade", mas fique a vontade para sugerir algo, talvez, mais coerente.

Pontos importantes:

- Nós também já buscamos esta informação de Código de Grupo de Cliente em nossa View:

![image](https://user-images.githubusercontent.com/27302062/28878407-a13230c6-7775-11e7-86b3-755cde223336.png)

Com isso, após você tratar o recebimento desta informação, nós vamos ajustar no "comando insert" para que a OTIF seja alimentada com este código também.

- Mesmo que este parâmetro faça com que a quantidade seja "sugerida" automaticamente nos carregamentos dos clientes que compoem o Grupo parametrizado, ainda assim, os campos para informar as quantidades ao acessar cada Carregamento devem continuar disponíveis para edição, caso seja necessário ajustar algum carregamento.

- Esta nova informação não precisa ser exibida na tela de Carregamentos, somente na tela deste Parâmetro, para escolher o código de Grupo de Cliente.

**Comment by engrogerio** [comment]
Adicionar a funcionalidade de Informar uma Quantidade Sugerida de um Produto específico para um Grupo de Clientes específico.É isso? 
Qual é esse campo de Quantidade ?Ele existe hoje?
Hoje não há um cadastro de grupo de clientes.
1 grupo pode ter n clientes ? 
E um cliente pode pertencer a mais de 1 grupo? 
Um cliente pode não pertencer a nenhum grupo?

**Comment by derikf** [comment]
Não é bem isso.
Para o Grupo de Cliente informado neste parâmetro, as Quantidades de Embalagens das notas fiscais (em vermelho), serão sugeridas (copiadas) automaticamente para as Quantidades Carregadas (em azul), porém, mantendo a possibilidade de edição do campo:

![quantidades](https://user-images.githubusercontent.com/27302062/29030556-cee62f8c-7b61-11e7-95b2-a1c39d2091c4.png)

- Sim, este campo já existe na tela de Carregamentos conforme acima;
- Não há cadastro e não precisar ter. Nós somente queremos que você carregue os códigos destes Grupos, pois nós já tratamos este código na View que importa as informações, e depois somente inserir no sistema OTIF. Talvez precise de uma tabela nova ou só acrescentar algum campo em alguma tabela, mas não precisa de uma tela de cadastro de grupos, pois isto é feito no Totvs;

- Sim, 1 grupo tem N clientes;
- Não, 1 cliente é de 1 grupo;
- Não também;
- Não. Todos os clientes possuem grupos.

**Comment by derikf** [comment]
Veja, o código de Grupo de Cliente já é buscado na View:

![image](https://user-images.githubusercontent.com/27302062/29030957-18b65a96-7b63-11e7-821d-21b13aebf348.png)

**Comment by engrogerio** [comment]
Perguntas:
1- Onde serão indicados os grupos que terão as quantidades  copiadas para os campos de quantidade carregada?
2- Porque não podemos simplesmente copiar todas as quantidades automaticamente para todos os registros?

**Comment by derikf** [comment]
1- Neste ponto seria a criação de um parâmetro onde informaremos os grupos que vão utilizar esta função.
2- Porque isto é necessário para 1 cliente específico neste momento. Mas se funcionar bem, usaremos para outro. A gerência das fábricas não quer liberar para todos, pois querem ter maior controle sobre as informações.

**Comment by engrogerio** [comment]
Acho que o assunto seria resolvido com os passos:
1- Colocar o Grupo na tela de clientes.
2- Criar uma tela simples para adicionar grupos.
3- Implementar a funcionalidade de copiar os valores.

**Comment by derikf** [comment]
@engrogerio 

Considerações:

1) Esta informação na tela de clientes seria apenas para exibição ? Acredito que não entendi o motivo para informar/mostrar o grupo do cliente na tela.

2) Esta tela já seria para informar o parâmetro para o grupo que será utilizado ? Pois se for uma nova tela para cadastro de grupo, não vejo necessidade, pois o código do grupo já vem vinculado ao cliente, conforme te mostrei acima.

3) Sim, concordo.

**Comment by engrogerio** [comment]
Ok. Vou trabalhar em criar uma tela para seleção de quais grupos devem ter a quantidade copiada para os campos Quantidade Carregada. Vai se chamar Pré carregamento. Ok?

**Comment by derikf** [comment]
Ok. Concordo.
Por favor, realizar um orçamento deste caso também e nos enviar.

Obrigado.

**Comment by engrogerio** [comment]
Um grupo é somente um número (conforme vc mostrou que já traz na view) ou deve ter uma descrição?
Quando você for selecionar quais grupos vão ter a quantidade automática, você vai selecionar os números dos grupos ou um nome?

**Comment by engrogerio** [comment]
Devemos copiar os valores para a quantidade carregada no evento da chegada do caminhão ou no inicio do carregamento?

**Comment by derikf** [comment]
Respondendo ao primeiro questionamento:

- Sim, o grupo é somente o número. Não tem descrição - pelo menos não neste sistema.
- Para simplificar tanto a seleção quanto a manutenção desta tela, vamos selecionar números de grupos.

**Comment by derikf** [comment]
Respondendo ao segundo questionamento:

- Copiar as quantidades no início do carregamento, pois é neste momento em que a produção tem a informação correta se vai faltar quantidade ou não.

**Comment by engrogerio** [comment]
Implementado no ambiente web. Testar e informar.
