### ISSUE TITLE
Status na tela de Carregamento

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#55]
Na tela de carregamento o calculo do Status não está sendo feito corretamente. Não sei com base em quê está sendo calculado, vou detalhado o que seria o correto.
O correto é que o calculo seja feito com base na grade + o limite.
Por exemplo: 
Grade do cliente é para 14h e os limites são: 30 min para chegada do caminhão e 2h para a liberação.

Se for assinalado o a chegada do caminhão até as 14:30 do dia da grade, então está no horário, depois disto está em atraso.
Para a liberação, se for liberado até as 16h está no horário, depois disto está em atraso.

**Comment by angelitakoehler** [comment]
Nos teste adicionais que fiz hoje com a usuária, identificamos que parece que o problema está porque na capa do carregamento está sempre assumindo a hora atual no momento que sinalizamos a chegada do caminhão e isto deveria sempre ser a hora da grade.
** excluido parte deste issue para criação de um novo **

**Comment by angelitakoehler** [comment]
Conforme conversamos eu fiz mais testes disto na base de testes, mas na verdade não consegui chegar a uma conclusão. Porque o cálculo não está sendo feito de maneira correta, mesmo eu atribuindo a grade direito, não sei com que ele está comparando para definir o status, mas aparentemente não esta pegando do lugar certo, porque não está entendendo os limites.
Além disso, se eu atualizar a chegada do caminhão em um horário, e depois ver que está errado, quando eu faço uma correção desta informação ele não recalcula o status. Deveria recalcular do contrario fica com uma posição incorreta.

**Comment by engrogerio** [comment]
Se vc necessita selecionar a mesma grade para vários ítens da lista da capa, os ítens selecionados, devem ser para a mesma unidade e mesmo cliente. O que fazer se isso não for verdade?

**Comment by angelitakoehler** [comment]
Da mesma unidade sim, do mesmo cliente não, pois eu posso ter vários clientes dentro de um mesmo carregamento ou passagem.
Se for selecionado mais de uma unidade, dê uma mensagem informando não ser possível executar a ação pois foram selecionados documentos de unidades diferentes.

**Comment by engrogerio** [comment]
Angelita. 
A regra que está no sistema hoje é a que me foi passada no início do desenvolvimento. (abaixo)
Note que a regra de chegada do caminhão está diferente do que você passou neste issue.
Qual devemos manter? Grade - Limite ou Grade + Limite?

Limite Chegada caminhao
Calculado (Se Hr de chegada > (data e Hr Grade **-** Limite carga da tabela
ARZ_LIMITE_CLIENTE) então "Atrasado" senão "No Horário")
Limite Liberação caminhão
Calculado (Se Hr de Liberação > (data e Hr Grade + Limite Liberacao da tabela
ARZ_LIMITE_CLIENTE) então "Atrasado" senão "No Horário")

**Comment by angelitakoehler** [comment]
Eu provavelmente te passei a formula errada em algum momento.

O que precisa ser feito é conforme este exemplo:
Horário da grade: 14:00
Limite: 30 min

Caminhão chegou até as 14:30 está no horário, após isto está atrasado.

Da mesma forma a regra para a liberação:
Grade: 14:00
Limite: 5:00

Caminhão liberado até as 19:00 está no horário, após este horário está atrasado.

Att,

**Comment by derikf** [comment]
@engrogerio 

- Os cálculos de “No horário” e “Atrasado” estão corretos de acordo com a grade informada;
- A tela não está mostrando a Data Programada:
 
![erro](https://user-images.githubusercontent.com/27302062/31173842-8547b8fe-a8df-11e7-84b3-68d21317d424.png)

- Quando sinalizamos a chegada do caminhão, sem informar o horário da grade no campo solicitado, está acusando um erro que não deixa claro para o usuário qual é o problema:

![erro1](https://user-images.githubusercontent.com/27302062/31173847-8b642c0e-a8df-11e7-9d8e-0d2a13ec06c8.png)

**Comment by engrogerio** [comment]
Ok. Corrigido.
Testar no ambiente nuvem.
