### ISSUE TITLE
Filtro na tela de Carregamento

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#56]
Gostaríamos de ter a possibilidade de na tela de carregamento, além de selecionar as rotas para o filtro, também filtrar tudo o que a rota está em branco, é possível incluir este filtro?
Porque temos uma situação em que queremos todos os carregamentos de um determinado transportador mas somente o que a rota está em branco.
Obrigada,

**Comment by engrogerio** [comment]
Por favor, informe se você conseguiu fazer funcionar o filtro alterando a query que grava os dados.

**Comment by angelitakoehler** [comment]
Alterei a rotina de carga de informações e também a base já carregada.
O filtro funcionou corretamente.
Estou encerrando a issue.
