### ISSUE TITLE
Tela de carregamento - Descrição do Produto

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#6]
Campo deveria trazer a descrição do produto e não apenas o código, assim facilita identificação do mesmo.

**Comment by engrogerio** [comment]
Você deixou ao meu cargo escolher:

On 11/03/2016 11:42 AM, Angelita Koehler wrote:

...
    A descrição do produto não trouxe para esta tabela, pois poderia ser lida direto da base Totvs que fica no mesmo banco em outro owner, porém o owner da Otif tem acesso.
    Se achar que devemos incluir isso nesta tabela, sem problema eu incluo e trago a informação.

Confirme se você deseja isso mesmo.

**Comment by angelitakoehler** [comment]
deixei a seu cargo escolher onde a descrição deveria estar e não a existência ou não dela.

**Comment by engrogerio** [comment]
Ok, Será incluido o campo ds_produto na tabela de item.

**Comment by engrogerio** [comment]
preciso de um excel com código / descrição para subir para o teste.Pode me enviar por email...

**Comment by angelitakoehler** [comment]
Segue exemplo
[ExemploItens.xlsx](https://github.com/engrogerio/sgo/files/711202/ExemploItens.xlsx)

**Comment by engrogerio** [comment]
Estes códigos não tem relação com os produtos cadastrados no db de teste, então, deixei a descrição aparecendo como "Produto - ds_produto" em cinza para cada linha de item de carregamento.

**Comment by angelitakoehler** [comment]
Os produtos que eu enviei no exemplo são exatamente os mesmo que eu enviei no arquivo que enviei com o exemplo de base.
Não sei de onde vc tirou os dados da sua base teste, só posso responder por aquilo que eu te enviei.

**Comment by angelitakoehler** [comment]
OK, vamos verificar a descrição do produto quando migrarmos para a base na Aryzta.
