### ISSUE TITLE
Tela de alteração de status de carregamento por bloco - adicionar campo para entrar grade.

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#60]
A sugestão é no momento de fazer a sinalização da chegada do caminhão, quando abre aquela tela de parâmetros, para poder atribuir a vários carregamentos o mesmo horário, incluir também um campo para informar qual era o horário de grade destes carregamentos selecionados. Mas isto somente faz sentido no momento que vou sinalizar a chegada do caminhão , nas demais etapas, não deveria abrir isso denovo.

**Comment by engrogerio** [comment]
Deixamos os 2 campos de Data? Data / Hora e Grade Data / Hora ?
Qual seria a ação do botão de inserir a data atual ? inserir a mesma data em ambos os campos?

**Comment by engrogerio** [comment]
Concluido. Implementar em produção.

**Comment by derikf** [comment]
Validado. Está correto.
