### ISSUE TITLE
Nova coluna tela de Carregamentos

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#61]
Rogério,

Precisamos de uma nova coluna na tela de Carregamentos. Nesta coluna devem ser apresentados os Motivos, cadastrados na tela "Motivos".

![image](https://user-images.githubusercontent.com/27302062/31293772-cca7c9d4-aaae-11e7-81c4-a31bf6e9454e.png)

![image](https://user-images.githubusercontent.com/27302062/31293782-d5c6a3fa-aaae-11e7-96b5-d49c5d56ea35.png)

E estes mesmo motivos são informados dentro de cada Carregamento:

![image](https://user-images.githubusercontent.com/27302062/31293932-6ca71ed0-aaaf-11e7-8565-2bcd1554b97c.png)

Adicionar um filtro de carregamentos por Motivo.
Por favor, enviar um orçamento para análise e aprovação.

Obrigado.

**Comment by engrogerio** [comment]
Hoje isso serve para cada **item** do carregamento.
Você quer criar um novo campo de motivo para o carregamento ?

**Comment by engrogerio** [comment]
Coloquei esta solicitação no 62

**Comment by derikf** [comment]
Não é necessário um campo para motivo de carregamento.
Na tela de carregamento, na coluna nova, pode mostrar somente os códigos agrupados mesmo entende ?

Coluna: Motivos
Conteúdo: 1,5,6,7

Não precisa mostrar a descrição de cada.

**Comment by derikf** [comment]
Acrescentar nesta coluna, para aparecer também os motivos de Atrasos no Carregamento, conforme Issue #63 .

**Comment by derikf** [comment]
@engrogerio 

Boa tarde,
Algum retorno sobre este caso ?

**Comment by engrogerio** [comment]
Entedi que você quer um campo no Carregamento para selecionar um dos motivos já existentes (mesmos motivos dos itens de carregamento) como motivo de atraso.
Esta solicitação não é a mesma do #63 ?

**Comment by derikf** [comment]
Sim, verdade. Vou encerrar esta Issue e comentar na #63 .
