### ISSUE TITLE
Novo filtro na tela de Carregamentos

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#62]
Rogério,

Precisamos de um novo filtro na tela de Carregamentos.
Este filtro deve buscar os Motivos que foram inseridos nos carregamentos:

![image](https://user-images.githubusercontent.com/27302062/31294244-8d667804-aab0-11e7-9123-6d4624fed87c.png)

Por favor, enviar um orçamento para análise e aprovação.

Obrigado.

**Comment by engrogerio** [comment]
Coloquei esta solicitação no #61
