### ISSUE TITLE
Motivos de Atraso

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#63]
@engrogerio 
Além dos Motivos de Faltas que são informados por itens, nós também temos Motivos de Atrasos de carregamentos, que são informados para os respectivos carregamentos.

Precisamos que seja incluído na tela de Carregamentos, um campo para selecionarmos os Motivo de Atraso daquele carregamento:

(Sugestão de local do campo)
![image](https://user-images.githubusercontent.com/27302062/31614381-0ebcc6ea-b265-11e7-98e4-f89e66e5fb03.png)

Este campo precisar ser uma lista para selecionarmos o Motivo, assim como é feito com os Motivos de Falta:

![image](https://user-images.githubusercontent.com/27302062/31614481-553d8df2-b265-11e7-8d84-c6e5f34876b8.png)

Além disto, na "capa do carregamento", precisamos que seja adicionada na lista de ações, uma opção para: "Informar Motivo de Atraso", também com a possibilidade de marcar um ou mais carregamentos.

![image](https://user-images.githubusercontent.com/27302062/31615486-7af8d30a-b268-11e7-8846-0ce5e2c3070d.png)

Por favor, realizar o orçamento desta alteração e nos enviar para análise e aprovação.

Obrigado.

**Comment by derikf** [comment]
@engrogerio 
Acrescentando:

Seria bom também se, no momento em que o usuário escolher a Ação - Inserir Motivo de Atraso, na nova janela que abrir, aparecer também o campo de observação para digitar algo mais pontual, se necessário.

Favor orçar com essa alteração também.

Obrigado,

**Comment by derikf** [comment]
@engrogerio 

Boa tarde Rogério,
Algum retorno sobre este caso ?

Obrigado,

**Comment by engrogerio** [comment]
Você necessita selecionar vários motivos de atraso para cada carregamento ou sempre será um só motivo?

**Comment by derikf** [comment]
Respondendo a pergunta acima, sim, pode ocorrer de um mesmo Carregamento ter mais de 1 motivo de atraso e/ou falta.

Edição: Não, cada Carregamento somente pode ter 1 motivo. Não pode ter mais de um motivo.

**Comment by derikf** [comment]
Referente a Issue #61 , favor acrescentar um filtro na coluna de "Filtros" do lado direito, para buscar Carregamentos que tiveram qualquer Motivo, tanto de Atraso quanto de Falta informados.

**Comment by derikf** [comment]
Editei o comentário acima.

**Comment by engrogerio** [comment]
1- O cadastro de Motivos de Faltas atual pode comportar tambem os motivos de Atraso de Carregamento ou temos que criar um cadastro separado? E quanto ao issue 67 de cadastro de Motivos de Alteração de Agendamento? 
2- No caso de deixar apenas um motivo de atraso para o carregamento, podemos usar o campo de obs já existente para observações do atraso?

**Comment by angelitakoehler** [comment]
Seguem respostas:
1 - Você pode utilizar sempre o mesmo cadastro de motivos, mas precisa identificar 2 informações:
    a.) Que tipo de motivo é - Falta, Atraso ou Agendamento, pois quando o usuário abrir a lista de motivos, cada tela deve mostrar apenas os seus motivos, e não todos.
   b.) Informar se impacta OTIF ou não (para as faltas sempre impacta, para os outros, pode ou não impactar)

2 - Não, o campo de observação já existente na tela é para ambos os motivos - Atraso e Falta, porém o novo campo de observações solicitado é específico para informações sobre agendamento e isto não pode ser misturado. Lembrando que logística não altera os motivos nem as observações referentes a falta e atraso, e os demais usuários não alteram as informações, motivos ou observações do agendamento.

**Comment by engrogerio** [comment]
1- Os mesmos usuários podem cadastrar qualquer motivo seja de Falta, Atraso ou Agendamento?

**Comment by derikf** [comment]
1- Os motivos de Falta e de Atraso os mesmos usuários podem cadastrar; Mas os motivos de Agendamento não, são outros usuários específicos.
