### ISSUE TITLE
Melhorar seleção de filtros

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#64]
@engrogerio 

- Filtro de Rotas:
Teria como melhorar a seleção do filro de Rotas ? 
Pois está um filtro muito extenso e pode dificultar na consulta. Tem como fazer uma caixa expansiva parecida com a seleção dos motivos de falta ?

- Botão Reset nos filtros:
Percebemos que este botão Reset limpa somente o período selecionado no filtro.
Tem como fazer com que este botão limpe todos os filtros ativos/selecionados ?

Obrigado.

**Comment by derikf** [comment]
@engrogerio 

Boa tarde,
Por favor nos enviar um orçamento antes de efetuar a alteração.

Obrigado,

**Comment by engrogerio** [comment]
Pode ser conforme abaixo?:

![image](https://user-images.githubusercontent.com/6229885/31853755-e007099e-b66c-11e7-9e3d-a5e2d84fb794.png)

**Comment by engrogerio** [comment]
Sobre o botão , estou investigando ainda...

**Comment by derikf** [comment]
Se eu entendi, ao clicar na seta do lado esquedo do nome do filtro, ele vai expandir as demais opções correto ?
Se for assim, concordo. Pode ser.

**Comment by engrogerio** [comment]
implementado no ambiente web. Testar e informar.
