### ISSUE TITLE
Entregas necessárias para 03/11/17

### ISSUE THREAD

**Issue by angelitakoehler** [engrogerio/sgo#65]
Rogerio,
Temos alterações no sistema de OTIF que precisam ser cotadas.
Vou descrever tudo aqui, fique a vontade para separar em outras issues se achar pertinente, mas isto é o que precisamos que seja entregue também para entrar em produção no dia 03/11:

Precisamos de mais algumas informações no sistema, que serão alimentadas de formas diferentes:
-> Motivos de alteração em agendamento:
	- Será necessário um cadastro de motivos de alteração do agendamento, e nestes motivos deverá ser possível indicar se o motivo impacta OTIF ou não.
	- Este cadastro também deverá ser permitido liberar para pessoas específicas, ainda não está definido quem deverá realizar este cadastramento.

-> Data /hora de Agendamento
	- Esta data deverá ser alimentada por logística, que não terá acesso a informar/alterar as demais informações que são relativas ao carregamento
	- Esta informação é necessária apenas para os pedidos que possuem frete do tipo FOB.
	- Esta informação é alimentada antes do faturamento, portanto quando ela é inserida no sistema, ainda não temos no número da Nota fiscal.
	- Também é necessário manter o log das alterações, pois esta informação poderá ser alterada a qualquer tempo.
- Deverá ser obrigatório escolher o motivo no momento da inclusão da informação de data de agendamento, caso a data de agendamento seja posterior à data de entrega prevista no pedido.
	- Deverá ser obrigatório escolher o motivo sempre que houver uma alteração nas informações do agendamento;

-> Protocolo do agendamento
	- Isto é um campo texto, com no máximo 100 caracteres.
-  Esta informação deverá ser solicitada sempre que preencher/alterar a data de agendamento.

-> Observações do agendamento
	- Campo texto livre, não mandatório;
	- Deverá ser possível inserir/alterar no momento do registro ou alteração do agendamento.

-> Data /hora de chegada no cliente 
	- Preparar este campo na base de dados, porém neste momento, para agilizar a entrega a Aryzta vai alimentar via banco a importação estes dados direto para a base.

-> Data /hora da entrega efetiva (descarga)
	- Preparar este campo na base de dados, porém neste momento, para agilizar a entrega a Aryzta vai alimentar via banco a importação estes dados direto para a base.

Além destas informações adicionais, que serão alimentadas por pessoas/áreas diferentes, precisamos ter uma tela onde seja possível consultar todas estas informações e as que já estão no sistema atualmente (carregamento).
Deverá ser apresentado um status a mais nesta consulta:
Se o frete for FOB, e a data/hora de chegada no cliente for posterior à data/hora de agendamento, o status deverá ser em atraso.

**Comment by engrogerio** [comment]
Fechado pela criação dos issues #67 e #68
