### ISSUE TITLE
Grupo de Cliente e Pre Carregamento

### ISSUE THREAD

**Issue by derikf** [engrogerio/sgo#69]
@engrogerio 
Durante nossas validações, identificamos que tem 2 novas telas: Grupo de Clientes e Pré Carregamento.

Pelo que entendi, essas telas tem relação com as cópias das quantidades correto ?
O funcionamento seria algo parecido com:

- Selecionar uma ou mais lojas na tela Grupo de Clientes, e com isso, criar um "Grupão" com essas lojas ?
- Depois, informar este "Grupão" na tela de Pré Carregamento para que as quantidades sejam copiadas ?

Seria isso ? Ou é de outra forma ?

Obrigado,

**Comment by derikf** [comment]
Isto é referente a #51 correto ?

**Comment by engrogerio** [comment]
Correto:
1- No Grupo de Clientes: Crie um grupo e adicione os clientes do grupo
2- No icone "Pré carregamentos", entre na unica linha "Grupos de pre carregamento"
3- Adicione um ou vários "grupos disponíveis" para a coluna "Grupos escolhidos"

**Comment by derikf** [comment]
Entendi.
Ok, testaremos mais vezes este processo.

**Comment by engrogerio** [comment]
Mesmo da iss #51
