### ISSUE TITLE
Tela de Carregamento - informar somente a quantidade carregada.

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#7]
Está solicitado informar a quantidade em falta, e não permite informar a quantidade carregada, deveria ser o contrario, informar a quantidade carregada e calcular o que faltou

**Comment by engrogerio** [comment]
Você tem razão.Será alterado para ficar dessa forma.

**Comment by angelitakoehler** [comment]
Ok Pode encerrar.
