### ISSUE TITLE
Tela de Carregamento - Campo para o Motivo da Falta

### ISSUE THREAD

**Issue by engrogerio** [engrogerio/sgo#8]
Não encontrei local para registrar o motivo em caso de falta, se há falta o motivo deveria ser obrigatório

**Comment by engrogerio** [comment]
Em um email de 1/12/2016, perguntei:
...
2- Nos items do pedido , há um campo "Observação / motivo". Crio 2 campos? Um para Obs e outro para escolher o Motivo (do cadastro acima)? O mesmo usuário preencherá ambos? Pode explicar se você precisa de 1 ou 2 campos aqui?
...
e você respondeu em 2/12/2016:
... 
Já na informação que é alimentada pela expedição, no carregamento, sempre que houver algum problema com a carga de um item (atraso, falta, etc) eles deverão escolher na lista um dos motivos que está previamente cadastrado na tabela de motivos para justificar o que houve. Não é necessário dois campos, precisa apenas registrar o código do motivo a descrição já está na tabela de cadastro.
...
Por favor, esclareça se necessita desse campo e se necessário, ele pode ser na tela de Fill Rate?

**Comment by angelitakoehler** [comment]
Você criou uma tela para cadastrar os motivos... 
Preciso que estes motivos sejam informados no local correto.
Por favor, observe que no documento de especificação (Detalhamento Informações OTIF.xlsx) na pasta Expedição em nível de item, é solicitado o motivo que está com descrição "Observação/Motivo" e indica que isto deverá ser escolhido na lista com base no que foi cadastrado na Tabela ARZ_MOTIVO_CAR que foi o nome sugerido.
Portanto o que preciso é que seja permitido informar o motivo da falta de produto e este motivo deverá ser um dos cadastrados.

**Comment by engrogerio** [comment]
O campo Motivo será incluido nos ítens dos pedidos.

**Comment by angelitakoehler** [comment]
Ok, o campo foi incluído,.
